swagger: "2.0"
host: "0.0.0.0:5000"
basePath: "/twirp"
schemes:
- "http"
paths:
  /twitch.twirp.example.haberdasher.Haberdasher/MakeHat:
    post:
      operationId: "MakeHat"
      consumes:
      - "application/json"
      - "application/protobuf"
      produces:
      - "application/json"
      - "application/protobuf"
      parameters:
      - in: "body"
        name: "Size"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/Size"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Hat"
definitions:
  Size:
    type: "object"
    properties:
      inches:
        type: "integer"
        format: "int32"
  Hat:
    type: "object"
    properties:
      size:
        type: "integer"
        format: "int32"
      color:
        type: "string"
      name:
        type: "string"
